name: CI Build
on:
  push:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - id: repo
        run: echo "repo=`echo ghcr.io/${{ github.repository }} | tr '[:upper:]' '[:lower:]'`" >> $GITHUB_OUTPUT
      - id: branch
        run: echo "branch=`echo ${{ github.ref }} | sed -e 's/refs\/heads\///g'`" >> $GITHUB_OUTPUT
      - id: commit
        run: echo "commit=`git rev-parse --short HEAD`" >> $GITHUB_OUTPUT
      - uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: |
            ${{ steps.repo.outputs.repo }}:${{ steps.branch.outputs.branch }}-${{ steps.commit.outputs.commit }}
