name: CI tests
on:
  push:
    branches: [ '**' ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: yarn
      - run: yarn lint
      - name: Logs collecting
        if: ${{ always() }}
        run: find ~/.npm/_logs -type f | xargs cat
        
